"""Exercise model for LearnFlow platform."""
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, Text, Float, Enum
from sqlalchemy.orm import relationship
import enum
from backend.src.models.base import Base


class DifficultyLevel(str, enum.Enum):
    """Exercise difficulty level enumeration."""
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class Exercise(Base):
    """
    Represents a dynamically generated practice exercise.

    Exercises are generated by the ExerciseGeneratorAgent based on
    student skill level and recent topics. Difficulty adapts based
    on student performance.

    Attributes:
        id: Unique exercise identifier
        title: Exercise title
        instructions: Detailed exercise instructions
        difficulty: Difficulty level (beginner, intermediate, advanced)
        topic: Python topic (e.g., "loops", "functions", "lists")
        test_cases: JSON string containing test cases for validation
        solution_template: Optional starter code for the student
        expected_output: Expected output description
        generated_at: Exercise generation timestamp
        generated_for_student_id: Student this was generated for (optional)
    """

    __tablename__ = "exercises"

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(255), nullable=False)
    instructions = Column(Text, nullable=False)
    difficulty = Column(Enum(DifficultyLevel), nullable=False, index=True)
    topic = Column(String(100), nullable=False, index=True)
    test_cases = Column(Text, nullable=False)  # JSON stored as text
    solution_template = Column(Text, nullable=True)
    expected_output = Column(Text, nullable=True)
    generated_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    generated_for_student_id = Column(Integer, nullable=True, index=True)

    # Relationships
    attempts = relationship("ExerciseAttempt", back_populates="exercise", cascade="all, delete-orphan")
    hints = relationship("Hint", back_populates="exercise", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Exercise(id={self.id}, title='{self.title}', difficulty='{self.difficulty}')>"

    def to_dict(self) -> dict:
        """Convert exercise to dictionary representation."""
        return {
            "id": self.id,
            "title": self.title,
            "instructions": self.instructions,
            "difficulty": self.difficulty.value if isinstance(self.difficulty, DifficultyLevel) else self.difficulty,
            "topic": self.topic,
            "test_cases": self.test_cases,
            "solution_template": self.solution_template,
            "expected_output": self.expected_output,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "generated_for_student_id": self.generated_for_student_id,
        }
