#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json
import sys
import subprocess
import os

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

def generate_agents_md():
    """Generate AGENTS.md from repo scan"""

    # Get repo root (3 levels up from this script)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    skill_dir = os.path.dirname(script_dir)
    repo_root = os.path.dirname(os.path.dirname(os.path.dirname(skill_dir)))

    # Run scan from repo root
    scan_script = os.path.join(skill_dir, 'scripts', 'scan_repo.py')
    result = subprocess.run(['python', scan_script],
                          capture_output=True, text=True, cwd=repo_root)

    if result.returncode != 0:
        print("✗ Scan failed")
        return 1

    data = json.loads(result.stdout)

    # Generate AGENTS.md content
    fence = "```"
    structure_lines = chr(10).join(f"{folder}/" for folder in sorted(data['structure'].keys())[:10])
    tech_lines = chr(10).join(f'- {tech}' for tech in data['tech_stack'])

    content = f"""# AGENTS.md

## Project Overview
This is the skills-library repository for Hackathon III: Reusable Intelligence and Cloud-Native Mastery.

## Tech Stack
{tech_lines}

## Project Structure
{fence}
{structure_lines}
{fence}

## Agent Instructions

### For All Agents (Claude Code, Goose, Codex)
- This repo contains reusable Skills in `.claude/skills/`
- Each skill follows the MCP Code Execution pattern
- SKILL.md files are under 100 tokens
- All heavy logic is in scripts/ folders
- Scripts return minimal output only

### Available Skills
1. agents-md-gen - Generates this file
2. kafka-k8s-setup - Deploys Kafka on K8s
3. postgres-k8s-setup - Deploys PostgreSQL on K8s
4. fastapi-dapr-agent - Scaffolds FastAPI + Dapr service
5. mcp-code-execution - MCP wrapper pattern template
6. nextjs-k8s-deploy - Deploys Next.js to K8s
7. docusaurus-deploy - Deploys Docusaurus docs

### How to Use a Skill
{fence}bash
# Via Claude Code or Goose
> Use the kafka-k8s-setup skill to deploy Kafka

# Manually
bash .claude/skills/kafka-k8s-setup/scripts/deploy.sh
{fence}

### Key Conventions
- Kubernetes namespaces: kafka, postgres, learnflow, dapr-system
- All commits follow format: "Agent: action description"
- Never load raw kubectl/API output into context
- Always wrap MCP calls in scripts

---
*Auto-generated by agents-md-gen skill*
"""

    # Write to repo root
    agents_md_path = os.path.join(repo_root, 'AGENTS.md')
    with open(agents_md_path, 'w') as f:
        f.write(content)

    print("✓ AGENTS.md generated")
    return 0

if __name__ == '__main__':
    sys.exit(generate_agents_md())
